### ISSUE TITLE
Attribute/API name change between 1.1.0 and 1.2.0?

### ISSUE THREAD

**Issue by SuperIRabbit** [facebookresearch/projectaria_tools#45]
We were using the following statement 
```
R = camera_model.get_transform_device_camera().rotation_matrix()
```
which worked in version 1.1.0 and 1.0.0, but in version 1.2.0 we are hitting the following error:
```
AttributeError: '_core_pybinds.sophus.SE3' object has no attribute 'rotation_matrix'
```
What should be the new attribute name?

cc @suyogduttjain

**Comment by SeaOtocinclus** [comment]
Hello,
Sorry about the inconvenience,
 
We gave the guidance in the section `[Known Issues] [Core]` about this API change here https://github.com/facebookresearch/projectaria_tools/releases/tag/1.2.0

**Comment by SeaOtocinclus** [comment]
Hello @SuperIRabbit, can you please close the issue if we answered your questions? else feel free to ask more details.

**Comment by SeaOtocinclus** [comment]
Closing the issue, feel free to reopen if needed.
