### ISSUE TITLE
Redefinition Error while buildling python bindings from source

### ISSUE THREAD

**Issue by ChenYutongTHU** [facebookresearch/projectaria_tools#170]
Dear Aria developers,

Thanks for the great work!

I followed this [instruction](https://facebookresearch.github.io/projectaria_tools/docs/data_utilities/installation/installation_python#building-python-bindings-from-source-advanced-user) to build python buildings from source.  I built it on Linux.

However, I ran into this issue multiple times:

/home/yutongchen/tang/cluster/yutongchen/code/projectaria_sandbox/projecta
ria_tools/build/temp.linux-x86_64-cpython-311/_deps/sophus-src/sophus/so3.hpp:88
8:7: error: redefinition of ‘class Eigen::Map<Sophus::SO3<Scalar_>, Options_>’
        888 | class Map<Sophus::SO3<Scalar_>, Options>
            |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      In file included from /home/yutongchen/tang/cluster/yutongchen/code/projec
taria_sandbox/projectaria_tools/build/temp.linux-x86_64-cpython-311/_deps/sophus
-src/sophus/se3.hpp:6

I found that in the C++ source code, some head files are used multiple times but it is almost impossible to manually fix them. I think there might be a common issue related to the platform and compilation backend.

Thanks for your help.

**Comment by SeaOtocinclus** [comment]
@ChenYutongTHU Thank you for your feedback.
Building from source is tested on our GitHub CI and successful so I wonder if your platform is having a slightly different configuration than what we expect.
in order to debug your compilation error we would need more information, such as your platform configuration (compiler version, Operating System and the CMake config log)

If you want, you can build in isolation using the instruction shared here https://facebookresearch.github.io/projectaria_tools/docs/data_utilities/installation/installation_python#building-python-bindings-from-source-with-a-package-manager

**Comment by ChenYutongTHU** [comment]
Hi. Thanks so much for your instruction.
I gave up building from source and found some alternatives instead. I will reopen this issue when needed.

**Comment by SeaOtocinclus** [comment]
CLosing the issue, as @ChenYutongTHU saying he will reopen the issue if needed.
